{
    'name': 'GEOSIS-PRO Proyectos',
    'summary': 'Proyectos vinculados a presupuestos para GEOSIS-PRO',
    'version': '17.0.1.0.0',
    'category': 'Technical',
    'author': 'GEOSIS-PRO',
    'website': 'https://geosis-pro.local',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'geosis_base',
        'geosis_presupuesto',
        'project',
        'project_timeline',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/geosis_project_rules.xml',
        'views/geosis_project_views.xml',
        'views/geosis_budget_extension_views.xml',
        'views/geosis_estimation_views.xml',
        'views/geosis_task_critical_views.xml',
    ],
    'installable': True,
    'application': False,
}
